import { triggerDownload } from './formats/excel'

export type ReportFormat = 'html' | 'pdf' | 'image'

export interface ReportRow {
  symbol: string
  label: string
  path: string
  before?: string
  after?: string
  colorHex: string
}

/** Builds a self-contained, portable HTML report (no external assets) from a flat row list. */
export function buildReportHtml(title: string, subtitle: string, rows: ReportRow[]): string {
  const rowsHtml = rows
    .map(
      (r) => `
      <tr>
        <td class="sym" style="color:${r.colorHex}">${escapeHtml(r.symbol)}</td>
        <td class="label" style="color:${r.colorHex}">${escapeHtml(r.label)}</td>
        <td class="path"><code>${escapeHtml(r.path)}</code></td>
        <td class="val">${r.before !== undefined ? `<code>${escapeHtml(r.before)}</code>` : ''}</td>
        <td class="val">${r.after !== undefined ? `<code>${escapeHtml(r.after)}</code>` : ''}</td>
      </tr>`,
    )
    .join('')

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", sans-serif; background: #f2f4f5; color: #141a1f; margin: 0; padding: 40px; }
  .wrap { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .subtitle { color: #4b5761; font-size: 13px; margin: 0 0 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 8px 10px; border-bottom: 2px solid #d7dde1; color: #4b5761; font-weight: 600; }
  td { padding: 7px 10px; border-bottom: 1px solid #e6eaec; vertical-align: top; }
  td.sym { width: 28px; font-weight: 700; text-align: center; }
  td.label { width: 110px; font-weight: 600; white-space: nowrap; }
  code { font-family: "SFMono-Regular", Menlo, monospace; font-size: 12px; }
  .footer { margin-top: 20px; color: #838f98; font-size: 11px; }
</style>
</head>
<body>
  <div class="wrap">
    <h1>${escapeHtml(title)}</h1>
    <p class="subtitle">${escapeHtml(subtitle)}</p>
    <table>
      <thead><tr><th></th><th>Change</th><th>Path</th><th>Before</th><th>After</th></tr></thead>
      <tbody>${rowsHtml}</tbody>
    </table>
    <p class="footer">Generated by Manifest — SAP Payload Toolbox</p>
  </div>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export function downloadHtmlFile(html: string, filename: string) {
  triggerDownload(new Blob([html], { type: 'text/html' }), filename)
}

/** Rasterizes a DOM element (e.g. the on-screen diff results panel) to PNG and downloads it. */
export async function downloadElementAsImage(el: HTMLElement, filename: string, backgroundColor: string) {
  const { default: html2canvas } = await import('html2canvas')
  const canvas = await html2canvas(el, { backgroundColor, scale: 2 })
  const blob: Blob = await new Promise((resolve, reject) =>
    canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('Could not render image.'))), 'image/png'),
  )
  triggerDownload(blob, filename)
}

/** Rasterizes a DOM element to a single-page PDF sized to match its content. */
export async function downloadElementAsPdf(el: HTMLElement, filename: string, backgroundColor: string) {
  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([import('html2canvas'), import('jspdf')])
  const canvas = await html2canvas(el, { backgroundColor, scale: 2 })
  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({
    orientation: canvas.width >= canvas.height ? 'landscape' : 'portrait',
    unit: 'px',
    format: [canvas.width, canvas.height],
  })
  pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height)
  pdf.save(filename)
}
